### ISSUE TITLE
Could this be leveraged to solve Kanban feature request - dynamic views

### ISSUE THREAD

**Issue by spcano01** [HananoshikaYomaru/Obsidian-Frontmatter-Generator#15]
https://github.com/mgmeyers/obsidian-kanban/issues/345

I'm thinking this should be able to solve this.  There has to be something that is changed when I drag a card from column/list to another column/list - that can then be used to generate/update Status/Priority or however you define your lists.  

Sorry for lame definition, but I saw your post for Projects, which was a possible solution to this. I'm going to use your plugin and see if I can limit it to Kanban folder, and solve this.

**Comment by HananoshikaYomaru** [comment]
Hi. Thanks for your interest. But I have no experience with the plugin. I guess you need to open an issue on their side to see if they want to solve it using frontmatter generator.
