### ISSUE TITLE
Multiple condition sets

### ISSUE THREAD

**Issue by jimbosis1000** [HananoshikaYomaru/Obsidian-Frontmatter-Generator#22]
Great app! I've been looking for a way to sync properties with tags for months and this does it perfectly.

It would be helpful though if there was a way to run multiple conditional statements. In my case I have a conditional set up to check file type and if it's 'Estimate', update tags based on 3 other fields, and set the received date based on date created. Took a bit of tinkering but that works. 

```
{...file.properties?.type === 'Estimate' 
? 
(() => 
{
    const date = new Date(file.stat.ctime);
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    const formattedDate = `${year}-${month}-${day}`;
    return {
      tags: [file.properties.status, file.properties.company, file.properties.type],
      received: formattedDate
    };
  }
)
() 
: 
{}}
```

I also want to update any file with a location field that has no type to an 'Estimate'. Again, was able to achieve this. 

Where I'm hitting the wall is combining the two. Ternary operators are new for me and I've had zero luck trying to nest them. 

I've actually got six or seven other conditions I'd like to run as well but I'm unclear how I would do that. 

Being able to input discrete conditions would be a great feature

**Comment by HananoshikaYomaru** [comment]
Hi, thanks for the kind words. 

you can input discrete condition using `if else`. The frontmatter template doesn't have to be a json, you can use function directly. 

```js
(() => {
    const test = Math.random(0,1) * 10;
    if(test < 1) return { test : 1 } ; 
    if(test < 2) return { test: 2 } ; 
    ...
})()
```

this is the IIFE syntax which will return a json. 

to format your code more easily, you can first type it in a code editor, or https://www.typescriptlang.org/play and then copy back to it.
